FROM archlinux

ARG USER=ci

RUN useradd -m aur

RUN pacman -Sy && pacman -S \
		base-devel ca-certificates curl git \
		make g++ unzip libasan libubsan \
		clang lld ninja-build sudo \
		python3 python3-conan \
		&& git clone https://aur.archlinux.org/yay.git . && makepkg -si --noconfirm

RUN pip install conan --break-system-packages

RUN useradd -m ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/${USER}/workspace
