FROM archlinux

ARG USER=ci

RUN useradd -m aur

RUN pacman -Sy && pacman -S \
		base-devel curl git \
		make gcc unzip \
		clang lld ninja sudo \
		python python-conan \
		&& git clone https://aur.archlinux.org/yay.git . && makepkg -si --noconfirm

RUN pip install conan --break-system-packages

RUN useradd -m ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/${USER}/workspace
