FROM archlinux

ARG USER=ci

RUN useradd -m aur

RUN pacman -Sy && pacman -S \
		base-devel curl git \
		make gcc unzip \
		clang lld ninja sudo \
		python \
		--noconfirm \
		&& git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm \
		&& yay -S conan-bin

RUN pip install conan --break-system-packages

RUN useradd -m ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/${USER}/workspace
