#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fmt/base.h>
#include <fmt/format.h>
#include <fmt/printf.h>
#include <format>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <variant>
#include <vector>
