FROM archlinux

ARG USER=ci

RUN pacman -Sy && pacman -S \
		base-devel curl git \
		make gcc unzip \
		clang lld ninja sudo \
		python python-pipx \
		--noconfirm \
		&& pipx install conan && pipx ensurepath
 		&& echo 'export PATH=$PATH:/root/.local/bin' >> ~/.bashrc

RUN useradd -m ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/${USER}/workspace
